echo -e "Beginning Ilaria single-glazed"
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_9_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_8_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_7_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_6_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_5_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_4_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_3_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_2_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_single_glazed_0_1_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.1
echo -e "Beginning Ilaria double-glazed"
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_9_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_8_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_7_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_6_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_5_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_4_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_3_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_2_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_0_1_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.1
echo -e "Beginning Autotherm single-glazed"
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_9_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_8_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_7_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_6_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_5_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_4_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_3_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_2_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_0_1_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.1
echo -e "Beginning Autotherm double-glazed"
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_9_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_8_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_7_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_6_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_5_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_4_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_3_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_2_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_0_1_litres_per_hour_31_x_50 --x-resolution 31 --y-resolution 50 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.1
