python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_8_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_8_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_7_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_7_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_7_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_7_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_6_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_6_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_6_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_6_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_5_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_5_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_5_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_5_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_4_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_4_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_4_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_4_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_3_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_3_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_3_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_3_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_2_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_2_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_2_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_2_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_1_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_1_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_1_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_1_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1