python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_1_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_2_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_3_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_4_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_5_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_6_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_7_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_8_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_9_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_10_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 11
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_12_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 12
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_13_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 13
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_14_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 14
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_15_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 15
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_16_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 16
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_17_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 17
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_18_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 18
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_19_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 19
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_20_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 20
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_25_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 25
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_30_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 30
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_35_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 35
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_40_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 40
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_45_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 45
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_50_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 50
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_55_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 55
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_60_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 60
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_65_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 65
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_70_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 70
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_75_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 75
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_80_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 80
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_85_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 85
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_90_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 90
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_95_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 95
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_single_glazed_100_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 100
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_10_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 11
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_12_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 12
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_13_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 13
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_14_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 14
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_15_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 15
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_16_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 16
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_17_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 17
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_18_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 18
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_19_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 19
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_20_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 20
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_25_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 25
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_30_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 30
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_35_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 35
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_40_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 40
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_45_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 45
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_50_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 50
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_55_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 55
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_60_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 60
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_65_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 65
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_70_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 70
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_75_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 75
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_80_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 80
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_85_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 85
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_90_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 90
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_95_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 95
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_single_glazed_100_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 100
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_1_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_2_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_3_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_4_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_5_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_6_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_7_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_8_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_0_9_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 0.9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 11
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_12_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 12
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_13_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 13
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_14_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 14
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_15_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 15
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_16_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 16
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_17_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 17
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_18_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 18
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_19_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 19
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_20_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 20
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_25_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 25
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_30_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 30
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_35_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 35
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_40_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 40
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_45_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 45
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_50_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 50
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_55_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 55
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_60_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 60
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_65_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 65
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_70_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 70
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_75_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 75
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_80_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 80
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_85_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 85
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_90_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 90
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_95_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 95
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/hpc_run_outputs/autotherm_double_glazed_100_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 100
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 11
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_12_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 12
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_13_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 13
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_14_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 14
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_15_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 15
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_16_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 16
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_17_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 17
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_18_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 18
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_19_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 19
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_20_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 20
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_25_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 25
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_30_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 30
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_35_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 35
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_40_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 40
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 45
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 50
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 55
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 60
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 65
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 70
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 75
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 80
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 85
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 90
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 95
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/hpc_run_outputs/ilaria_double_glazed_11_0_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0 --skip-analysis --mass-flow-rate 100
