echo -e Running...
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.9 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_single_glazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.3 --skip-analysis
echo -e First batch run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.9 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_unglazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.3 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis
echo -e Second batch run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.9 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.3 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
echo -e First three batches run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.9 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_single_glazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 0.3 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.9 --skip-analysis
echo -e First Ilaria batch run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_unglazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 0.3 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_9_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.9 --skip-analysis
echo -e Second Ilaria batch run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_8_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.8 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_7_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.7 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_6_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.6 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_5_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.5 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_4_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.4 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria.yaml --output output_files/april_week_4/ilaria_double_glazed_pc_0_3_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 0.3 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/autotherm_10_pipes_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_6_pipes.yaml --output output_files/april_week_4/autotherm_6_pipes_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
echo -e Third Ilaria batch run.
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/autotherm_10_pipes_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_6_pipes.yaml --output output_files/april_week_4/autotherm_6_pipes_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/autotherm_10_pipes_unglazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_6_pipes.yaml --output output_files/april_week_4/autotherm_6_pipes_unglazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/ilaria_10_pipes_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_6_pipes.yaml --output output_files/april_week_4/ilaria_6_pipes_single_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/ilaria_10_pipes_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_6_pipes.yaml --output output_files/april_week_4/ilaria_6_pipes_double_glazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis

python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm_10_pipes.yaml --output output_files/april_week_4/ilaria_10_pipes_unglazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers pv a p f --portion-covered 1 --skip-analysis
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilaria_6_pipes.yaml --output output_files/april_week_4/ilaria_6_pipes_unglazed_pc_1_0_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.
.yaml --layers pv a p f --portion-covered 1 --skip-analysis
echo -e Flow-rate runs...
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 10
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 9
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 8
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 7
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 6
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 5
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 4
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 3
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 2
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/autotherm_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/autotherm_single_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers dg g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/autotherm.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
python3.7 -m pvt_model --initial-month 9 --location system_data/london_ilaria/ --pvt-data-file system_data/pvt_panels/ilarias_panel.yaml --output output_files/april_week_4/ilaria_double_glazed_10_litres_per_hour_31_x_12 --x-resolution 31 --y-resolution 12 --decoupled --steady-state --steady-state-data-file system_data/steady_state_data/autotherm.yaml --layers g pv a p f --portion-covered 1 --skip-analysis --mass-flow-rate 1
