# This workflow will enforce that all mypy `type:ignore` comments are documented correctly.

name: Mypy Enforcement

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enforce mypy error declaration
        run: |
          /usr/bin/env bash enforcement/mypy_enforcement.sh
